steps:
  - name: Dockerfile Scan
    template: choreo/dockerfile-scan@v1
  - name: Docker Build
    template: choreo/docker-build@v1
  - name: Static Code Analysis
    template: sonar-qube
  - name: Vulnerability Scan
    template: choreo/trivy-scan@v1
templates:
  - name: sonar-qube
    inlineScript: |
      #!/bin/bash
      echo "Starting SonarQube scan..." 
    env:
      - name: SONAR_PROJECT_KEY
        value: "hello"
    volumeMounts:
      - name: "workflows-volume"
        mountPath: "/tmp"
    resources:
      requests:
        memory: 128Mi
        cpu: 100m
      limits:
        memory: 256Mi
        cpu: 200m
    
