steps:
  - name: Dockerfile Scan
    template: choreo/dockerfile-scan@v1
  - name: Docker Build
    template: choreo/docker-build@v1
  - name: Static Code Analysis
    template: sonar-qube
  - name: Static Code Analysis 2
    template: sonar-qube-2
    continueOn:
      failed: true
  - name: Vulnerability Scan
    template: choreo/trivy-scan@v1
templates:
  - name: sonar-qube
    inlineScript: |
      #!/bin/bash
      echo "Starting SonarQube scan..."
      echo $SONAR_PROJECT_VAL
      echo $SONAR_PROJECT_VALS
      echo $SONAR_PROJECT_VAL_1
      echo $SONAR_PROJECT_VAL_2
    env:
      - name: SONAR_PROJECT_KEY
        value: "hello"
      - name: SONAR_PROJECT_VAL
        value: "{{SECRETS.SAS_TOKEN}}"
      - name: SONAR_PROJECT_VALS
        value: "{{SECRETS.DB_PSWD}}"
      - name: SONAR_PROJECT_VAL_1
        value: "{{VARIABLES.DB_HOST}}"
      - name: SONAR_PROJECT_VAL_2
        value: "{{VARIABLES.var_one}}"
  - name: sonar-qube-2
    inlineScript: |
      #!/bin/bash
      echo "Starting SonarQube scan..."
      exit 1
