steps:
  - name: Dockerfile Scan
    template: choreo/dockerfile-scan@v1
  - name: Go Test
    template: go-test
  - name: Docker Build
    template: choreo/docker-build@v1
  - name: Vulnerability Scan
    template: choreo/trivy-scan@v1
templates:
  - name: go-test
    inlineScript: |
      #!/bin/bash
      echo "Starting Go test..."
      cd $REPOSITORY_DIR
      ls
      go test
