steps:
  - name: Dockerfile Scan
    template: choreo/dockerfile-scan@v1
  - name: Docker Build
    template: choreo/docker-build@v1
  - name: Static Code Analysis
    template: sonar-qube
  - name: Vulnerability Scan
    template: choreo/trivy-scan@v1
templates:
  - name: sonar-qube
    inlineScript: |
      #!/bin/bash
      echo "Starting SonarQube scan..."
  
